[network]
ip_addr = "10.162.233.5"
# ip_addr = "192.168.140.204"
ip_port = 11116

[execution]
performance_duration = 15000
performance_internal = 2000
crash_duration = 30000
malicious_duration = 20000