# Test Option Configuration
[throughput]
enable = true

[latency]
enable = true

[scalability]
enable = true
max = 2
internal = 1

# Security testing: crash and malicious behaviours
[crash]
enable = true
max = 2

[malicious]
enable = false
behaviour = "action1"