# Test Option Configuration
[throughput]
enable = false

[latency]
enable = false

[scalability]
enable = false
max = 8
internal = 2

# Security testing: crash and malicious behaviours
[crash]
enable = true
max = 2

[malicious]
enable = false
behaviour = "action1"