# Test Option Configuration
[throughput]
enable = false

[latency]
enable = false

[scalability]
enable = false
max = 4
internal = 1

# Security testing: crash and malicious behaviours
[crash]
enable = false
max = 10

[malicious]
enable = true
number_of_phase = 2
# optional behaviours:
# LeaderFeignDeath
# LeaderSendAmbiguousMessage
# LeaderDelaySendMessage
# ReplicaNodeConspireForgeMessages
behaviours = [
    # "LeaderFeignDeath", 
    # "LeaderSendAmbiguousMessage", 
    # "LeaderDelaySendMessage",
    "LeaderSendDuplicateMessage", 
    # "ReplicaNodeConspireForgeMessages"
    ]